### ISSUE TITLE
Fix script issues & remove redundant '_' in code & append csv content issue

### ISSUE THREAD

**Issue by brandboat** [goldmedal/jvm-profiler-KafkaConsumer#1]
Three issues:
1. Add missing $SPARK_HOME in `run-consumer.sh` and `run-LoseRate-consumer.sh`.
2. Remove redundant '_' in code since Uber/jvm-profiler doesn't append this char in topic name.
3. In `generate-result-flamegraph.sh` `cat $f > target/$PREFIX-result.folded` will append the last file to $PREFIX-result.folded. '>' should be '>>'.

**Comment by brandboat** [comment]
Fixed in #2.
ping @goldmedal

**Comment by goldmedal** [comment]
It has been solved by #2. Let's close it.
